require "bundler/gem_tasks"
require "rake/extensiontask"
require "rake/javaextensiontask"

GEMSPEC = eval(File.read(File.expand_path("../sample_gem.gemspec", __FILE__)))

if RUBY_PLATFORM =~ /java/
  Rake::JavaExtensionTask.new("sample_gem_ext", GEMSPEC) do |ext|
    ext.ext_dir = 'ext/sample_gem'
  end
else
  Rake::ExtensionTask.new("sample_gem_ext", GEMSPEC) do |ext|
    ext.ext_dir = 'ext/sample_gem'
    ext.cross_compile = true
    ext.cross_platform = ['x86-mingw32', 'x64-mingw32']
  end

  ENV['RUBY_CC_VERSION'].to_s.split(':').each do |ruby_version|
    platforms = {
      "x86-mingw32" => "i686-w64-mingw32",
      "x64-mingw32" => "x86_64-w64-mingw32"
    }
    platforms.each do |platform, prefix|
      task "copy:sample_gem_ext:#{platform}:#{ruby_version}" do |t|
        %w[lib tmp/#{platform}/stage/lib].each do |dir|
          so_file = "#{dir}/#{ruby_version[/^\d+\.\d+/]}/sample_gem_ext.so"
          if File.exists?(so_file)
            sh "#{prefix}-strip -S #{so_file}"
          end
        end
      end
    end
  end
end
